Dependency refresh (#203)
* Update maven to v3.8.6

* Update to SpringBoot v2.7.6

Also bumps other dependencies for plugins and testing frameworks.

* Revert refactoring change in Facebook bot

ERROR me.ramswaroop.jbot.core.facebook.models.Event - Error serializing object:
com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: me.ramswaroop.jbot.core.facebook.models.Event["patternFromEventType"])