Revert refactoring change in Facebook bot
ERROR me.ramswaroop.jbot.core.facebook.models.Event - Error serializing object:
com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: me.ramswaroop.jbot.core.facebook.models.Event["patternFromEventType"])